import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans, Prata, Cormorant_Unicase } from "next/font/google";
import "./globals.css";

const interFont = Inter({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-inter",
});

const plusJakartaSansFont = Plus_Jakarta_Sans({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-plus-jakarta-sans",
});

const prataFont = Prata({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-prata",
});

const cormorantUnicaseFont = Cormorant_Unicase({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-cormorant-unicase",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

if (process.env.NODE_ENV === "development") {
    import("@/mocks").then(({ startMock }) => startMock());
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interFont.variable} ${plusJakartaSansFont.variable} ${prataFont.variable} ${cormorantUnicaseFont.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
